# File: .github/workflows/ci.yml

name: Deploy to GitHub
run-name: Deploy branch "${{ github.ref_name }}"

permissions: 
    contents: read

on:
    push:
        # Liste des branches qui déclencheront l'action de déploiement lors d'un git push
        # N'oubliez pas de créer un environnement correspondant dans GitHub (dans "Settings" -> "Environments") pour chaque branche
        # Puis ajoutez le secret "STACKHERO_SSH_PRIVATE_KEY" et la variable "STACKHERO_ENDPOINT" dans cet environnement
        branches: [dev]

    pull_request:
        branches: [dev]

env:
    php_version: 8.5

jobs:
    test:
        runs-on: ubuntu-26.04
        concurrency:
            group: test-my-project-${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true
    
        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Initialize PHP ${{ env.php_version }}
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ env.php_version }}
                coverage: pcov

            - name: Print PHP version
              run: echo ${{ steps.initialize-php.outputs.php-version }}

            - name: Setup PHP with composer v2
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ env.php_version }}
                tools: composer:v2

            - name: Composer install
              run: |
                composer install --optimize-autoloader --no-interaction --prefer-dist
                
            - name: Test
              run: php ./vendor/bin/phpunit tests
  # 3. Déploiement
    deploy:
        name: Déploiement (GitHub Pages)
        runs-on: ubuntu-latest
        needs: test
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'

        permissions:
            contents: read
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            # Si ton site statique est dans /public
            - name: Upload Pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: ./public

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v5