# File: .github/workflows/ci.yml

name: Deploy to GitHub
run-name: Deploy branch "${{ github.ref_name }}"

permissions: 
    contents: read

on:
    push:
        # Liste des branches qui déclencheront l'action de déploiement lors d'un git push
        # N'oubliez pas de créer un environnement correspondant dans GitHub (dans "Settings" -> "Environments") pour chaque branche
        # Puis ajoutez le secret "STACKHERO_SSH_PRIVATE_KEY" et la variable "STACKHERO_ENDPOINT" dans cet environnement
        branches: [dev]

    pull_request:
        branches: [dev]

env:
    php_version: 8.3

jobs:
    test:
        runs-on: ubuntu-latest
        concurrency:
            group: test-my-project-${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true
    
        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Initialize PHP ${{ env.php_version }}
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ env.php_version }}
                coverage: pcov

            - name: Setup PHP with composer v2
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ env.php_version }}
                tools: composer:v2

            - name: Composer install
              run: |
                composer install --optimize-autoloader --no-interaction --prefer-dist
                
            - name: Test
              run: php ./vendor/bin/phpunit tests